name: deploy

description: run gleam checks and tests

inputs:
  gleam-version:
    description: gleam version
    required: false
    default: "1"
  erlang-version:
    description: erlang-otp version
    required: false
    default: "27"
  rebar3-version:
    description: rebar3 version
    required: false
    default: "3"
  module-name:
    description: the path of the gleam module to run
    required: false
    default: build
  dist-path:
    description: the path of the directory to be published as a github pages artifact
    required: false
    default: dist

runs:
  using: composite
  steps:
    - name: setup beam
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.erlang-version }}
        gleam-version: ${{ inputs.gleam-version }}
        rebar3-version: ${{ inputs.rebar3-version }}
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: build assets
      run: gleam run -m ${{ inputs.module-name }}
      shell: bash
    - name: publish github pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.dist-path }}
