name: deploy

description: run gleam checks and tests

inputs:
  gleam-version:
    description: gleam version
    required: false
    default: 0.33.0
  erlang-version:
    description: erlang-otp version
    required: false
    default: 26.1.2
  module-name:
    description: the path of the gleam module to run
    required: false
    default: build
  dist-path:
    description: the path of the directory to be published as a github pages artifact
    required: false
    default: dist

runs:
  using: composite
  steps:
    - name: setup beam
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ inputs.erlang-version }}
        gleam-version: ${{ inputs.gleam-version }}
    - name: build assets
      run: gleam run -m ${{ inputs.module-name }}
      shell: bash
    - name: compress assets
      uses: a7ul/tar-action@v1.1.3
      id: compress
      with:
        command: c
        files: ${{ inputs.dist-path }}
        outPath: github-pages
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: publish github pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{ inputs.dist-path }}
